name: C++ GA Testing

on:
  push:
    branches: [ main ]

jobs:
  ga-test:
    name: Solve GA for ${{ matrix.problem }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        problem: ["20.5.1", "20.5.2", "20.5.3", "20.5.4", "50.10.1", "50.10.2", "50.10.3", "50.10.4", "200.40.1", "200.40.2", "200.40.3", "200.40.4"]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Setup Data Directories
      run: |
        mkdir -p "D2D Problem/random_data"

    - name: Compile C++ Program
      run: |
        g++ -std=c++17 -fopenmp -O3 mul.cpp -o mul.exe

    - name: Run Program
      run: |
        PROBLEM_NAME="${{ matrix.problem }}"
        DATA_FILE="D2D Problem/random_data/${PROBLEM_NAME}.txt"

        if [ -f "$DATA_FILE" ]; then
          echo "Data file $DATA_FILE found. Running the program..."
          ./mul.exe "$PROBLEM_NAME"
        else
          echo "Data file $DATA_FILE not found. Skipping program execution."
        fi
  tsp-test:
    name: Solve TSP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        problem: ["a280", "att48", "berlin52", "ch130", "ch150", "eil51", "eil76", "eil101", "gr96", "gr202", "gr666", "kroA100", "lin105", "pcb442", "pr1002", "pr2392", "rd100", "st70", "tsp225"]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Setup Data Directories
      run: |
        mkdir -p "problems/tsp"
    - name: Compile C++ Program
      run: |
        g++ -std=c++17 -fopenmp -O3 tsp.cpp -o tsp.exe

    - name: Run Program
      run: |
        PROBLEM_NAME="${{ matrix.problem }}"
        DATA_FILE="problems/tsp/${PROBLEM_NAME}.tsp/${PROBLEM_NAME}.tsp"

        if [ -f "$DATA_FILE" ]; then
          echo "Data file $DATA_FILE found. Running the program..."
          ./tsp.exe "$PROBLEM_NAME"
        else
          echo "Data file $DATA_FILE not found. Skipping program execution."
        fi
